2026/04/02

diff --git a/progs/bin/rec b/progs/bin/rec
--- a/progs/bin/rec
+++ b/progs/bin/rec
@@ -1,80 +1,78 @@
-#!/bin/zsh
-
-setopt extendedglob
-setopt posix_jobs
+#!/bin/sh
 
 run() {
 
-opts=`getopt -l device:,time:,out:,help,verbose d:t:o:hv "$@"`
+opts=`getopt -l device:,time:,out:,start:,help,verbose d:t:o:s:hv "$@"`
 
 if [[ $? != 0 || $# == 0 ]]; then
-    msg invalid arguments
-    echo $usage >&2
-    exit
+    err "invalid arguments\m$usage"
 fi
 
-opts=(${(z)opts})
+eval set -- "$opts"
 
 out=/dev/stdout
-while true; do
-    name=$opts[1]
-    param=${(Q)opts[2]}
-    case $name in
+while test $# -ne 0; do
+    case $1 in
     -h|--help)
         echo $usage
         exit;;
     -d|--device)
-        devnum=$param
-        shift 2 opts;;
+        devnum=$2
+        shift 2;;
     -t|--time)
-        rectime=($rectime $param)
-        shift 2 opts;;
+        rectime=($rectime $2)
+        shift 2;;
     -o|--out)
-        out=$param
-        shift 2 opts;;
+        out=$2
+        shift 2;;
+    -s|--start)
+        start=$1
+        shift 2;;
     -v|--verbose)
         verbose=1
-        shift 1 opts;;
+        shift;;
     --)
-        shift opts
+        shift
         break;;
     esac
 done
 
-if [[ $#opts > 1 ]]; then
-    msg extra parameters: ${(Q)opts}
-    exit 1
-elif [[ $#opts == 0 ]]; then
-    msg missing channel
-    exit 1
+if test $# >= 2; then
+    shift
+    err extra parameters: "$@"
+elif test $# == 0; then
+    err missing channel
 fi
 
-channel=${(Q)opts[1]}
+channel=$1
 
-if [[ -z $devnum ]]; then
+if test -z "$devnum"; then
     verbose detect and lock device...
-    for i in `[[ $channel -lt 100 ]] && echo 9 11 || echo 8 10`; do
-        fuse_b25 -o allow_root /dev/dvb/adapter$i
-        if [[ $? == 0 ]]; then
+    if test $channel -lt 100; then
+        devnums="9 11"
+    else
+        devnums="8 10"
+    fi
+    for i in $devnums; do
+        fuse_b25 /dev/dvb/adapter$i
+        if test $? = 0; then
             devnum=$i
             break
         fi
     done
-    if [[ -z $devnum ]]; then
-        msg all device are busy or not found
-        exit 1
+    if test -z "$devnum"; then
+        err all device are busy or not found
     fi
 else
     verbose lock device...
-    fuse_b25 -o allow_root /dev/dvb/adapter$devnum
+    fuse_b25 /dev/dvb/adapter$devnum
     mounted=$?
-    if [[ $mounted != 0 ]]; then
-        msg device is busy or not found
-        exit 1
+    if test "$mounted" != 0; then
+        err device is busy or not found
     fi
 fi
 
-if [[ -n $verbose ]]; then
+if test -n "$verbose"; then
     verbose devnum: $devnum
     verbose rectime: $rectime
     verbose out: $out
@@ -82,26 +80,25 @@ if [[ -n $verbose ]]; then
 fi
 
 verbose tune...
-tune $devnum $channel &
+tune "$devnum" "$channel" &
 tunepid=$!
 sleep 0.1
 if ! pgrep -P $$ tune; then
     msg tune failed
 else
+    msg $tunepid
     verbose recording...
-    if [[ -n $rectime ]]; then
+    if test -n "$rectime"; then
         timeout --foreground $rectime cat /dev/dvb/adapter$devnum/dvr0 >$out
         exitcode=$?
-        if [[ $exitcode != 124 ]]; then
-            while !kill $tunepid || [ -d /proc/$tunepid ]; do ; done
-            exit $exitcode
-        fi
+        # if test $exitcode != 124; then
+        #     exit $exitcode
+        # fi
     else
         cat /dev/dvb/adapter$devnum/dvr0 >$out
-        exit 0
     fi
 fi
-while !kill $tunepid || [ -d /proc/$tunepid ]; do ; done
+kill $tunepid
 
 sleep 2
 fusermount -u /dev/dvb/adapter$devnum
@@ -110,39 +107,17 @@ exit $exitcode
 
 }
 
-cleanup() {
-    msg stopped by SIG$1
-    verbose stop recording...
-    if [[ -n $rectime ]]; then
-        pkill -$1 -P $$ timeout
-    else
-        pkill -$1 -P $$ cat
-    fi
-    verbose stop tuning...
-    pkill -P $$ tune
-    sleep 1
-    if [[ $mounted != 0 ]]; then
-        verbose unmount device...
-        fusermount -u /dev/dvb/adapter$devnum
-    fi
+msg() {
+    echo `basename $0`: "$@" >&2
+}
+err() {
+    msg "$@"
     exit 1
 }
-
-TRAPTERM() {
-    cleanup TERM
-}
-TRAPINT() {
-    cleanup INT
-}
-TRAPKILL() {
-    cleanup KILL
-}
-
-msg() {
-    echo tune2: "$@" >&2
-}
 verbose() {
-    [[ -n $verbose ]] && echo "$@" >&2
+    if test -n $verbose; then
+        echo "$@" >&2
+    fi
 }
 
 usage=\
@@ -154,4 +129,4 @@ options:
   -v --verbose        show verbose message
   -h --help           show this help'
 
-run $*
+run "$@"
